### ISSUE TITLE
Anuglar 4

### ISSUE THREAD

**Issue by Eventyret** [bradtraversy/proplistings#3]
Is this compatible with angular 4 by any chance?
Great videos anyways! Love the content

**Comment by SaifDeveloper** [comment]
Hey Brad ! in the Firebase Service file, is something wrong with the addListing() function ? 
When I submit the form, the request goes like a GET request-
http://localhost:4200/add-listing?title=TEST&city=TEST&owner=TEST&bedrooms=12&type=Apartment&image=house1.jpg&price=10m

I found that when I hit submit, the onAddSubmit() function in the add-listingComponent,ts file is not called. But, when I remove the following line, onAddSubmit() is called:
this.firebaseService.addListing(listing);

Please help.

Thanks

**Comment by Eventyret** [comment]
As this is not ment as a comment i will close it myself.
